platform-events/main/default/objects/AsynchronousProcessNotification__e/AsynchronousProcessNotification__e.object-meta.xml
<CustomObject>
    <label>Asynchronous Process Notification</label>
    <pluralLabel>Asynchronous Processes Notifications</pluralLabel>
</CustomObject>

asynchronous-process-notifier/main/default/objects/AsynchronousProcessNotification__e/fields/DisplayNotification__c.field-meta.xml
<CustomField>
    <fullName>DisplayNotification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>When no notification displays, you can just refresh view to see rollback data.</description>
    <label>Display Notification</label>
    <type>Checkbox</type>
</CustomField>

asynchronous-process-notifier/main/default/objects/AsynchronousProcessNotification__e/fields/ObjectApiName__c.field-meta.xml
<CustomField>
    <fullName>ObjectApiName__c</fullName>
    <description>Populate concerned record's object API name if you want allow user to navigate to the record's view from the toast notification and/or if you want to refresh record's view and/or object's related lists to see the rollback data.</description>
    <label>Object API Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

asynchronous-process-notifier/main/default/objects/AsynchronousProcessNotification__e/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <description>Set the concerned record ID to allow the user to navigate to the record&#39;s view page (only if the record name field is also populated). Also required if refreshing record&#39;s view is required (then, do not forget to inform object type field).</description>
    <inlineHelpText>Set the concerned record ID to allow the user to navigate to the record&#39;s view page (only if the record name field is also populated). Also required if refreshing record&#39;s view is required (then, do not forget to inform object type field).</inlineHelpText>
    <label>Record ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

asynchronous-process-notifier/main/default/objects/AsynchronousProcessNotification__e/fields/RecordName__c.field-meta.xml
<CustomField>
    <fullName>RecordName__c</fullName>
    <description>Mention of the record as it will display in the toast notification. Use the {0} index placeholder in your message to do so.</description>
    <inlineHelpText>Mention of the record as it will display in the toast notification. Use the {0} index placeholder in your message to do so.</inlineHelpText>
    <label>Record Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

platform-events/main/default/objects/AsynchronousProcessNotification__e/fields/RefreshObjectsListViews__c.field-meta.xml
<CustomField>
    <fullName>RefreshObjectsListViews__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Refresh the concerned object&#39;s list views to see data rolback when a user navigates on one of the object&#39;s list views.</description>
    <label>Refresh Object&#39;s List Views</label>
    <type>Checkbox</type>
</CustomField>

platform-events/main/default/objects/AsynchronousProcessNotification__e/fields/RefreshRecordsViewPage__c.field-meta.xml
<CustomField>
    <fullName>RefreshRecordsViewPage__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Refresh the concerned record&#39;s view page to see data rolback.</description>
    <label>Refresh Record&#39;s View Page</label>
    <type>Checkbox</type>
</CustomField>

platform-events/main/default/objects/AsynchronousProcessNotification__e/fields/ToastNotificationMessage__c.field-meta.xml
<CustomField>
    <fullName>ToastNotificationMessage__c</fullName>
    <label>Toast Notification Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

asynchronous-process-notifier/main/default/objects/AsynchronousProcessNotification__e/fields/ToastNotificationMode__c.field-meta.xml
<CustomField>
    <fullName>ToastNotificationMode__c</fullName>
    <description>Set the toast notification persistency. Valid values are: dismissable (default), pester or sticky.</description>
    <inlineHelpText>Set the toast notification persistency. Valid values are: dismissable (default), pester or sticky.</inlineHelpText>
    <label>Toast Notification Mode</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

platform-events/main/default/objects/AsynchronousProcessNotification__e/fields/ToastNotificationVariant__c.field-meta.xml
<CustomField>
    <fullName>ToastNotificationVariant__c</fullName>
    <description>Set toast notification variant: Valid values are: info (default), success, warning, and error.</description>
    <label>Toast Notification Variant</label>
    <length>8</length>
    <type>Text</type>
</CustomField>

asynchronous-process-notifier/main/default/objects/AsynchronousProcessNotification__e/fields/UsersToNotify__c.field-meta.xml
<CustomField>
    <fullName>UsersToNotify__c</fullName>
    <description>Salesforce IDs of users to notify, use the separator you wish. To notify ALL the users, do not populate this field.</description>
    <inlineHelpText>Salesforce IDs of users to notify, use the separator you wish. To notify ALL the users, do not populate this field.</inlineHelpText>
    <label>User(s) to Notify</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

asynchronous-process-notifier-test/main/default/classes/QueueableProcess.cls
public class QueueableProcess implements Queueable {
    
    private List<Contact> contacts;
    private Map<Id, Contact> oldContacts;
    private Id userId;
    
    public QueueableProcess(List<Contact> contacts, Map<Id, Contact> oldContacts, Id userId) {
        this.contacts = contacts;
        this.oldContacts = oldContacts;
        this.userId = userId;
    }
    
    public void execute(QueueableContext context) {
        Datetime dt = Datetime.now();
        // Artificial delay to fake a long-running process.
        while (Datetime.now() < dt.addSeconds(5)) {}
        List<Contact> contactsToRollback = rollbackContactsEmailAddresses(contacts, oldContacts);
        update contactsToRollback;
        List<AsynchronousProcessNotification__e> asynchronousProcessNotification = setAsynchronousProcessNotificationEvents(contactsToRollback, userId);
        EventBus.publish(asynchronousProcessNotification);
    }

    private static List<Contact> rollbackContactsEmailAddresses(List<Contact> contacts, Map<Id, Contact> oldContacts) {
        for (Contact ct : contacts) {
            if (oldContacts != null && !oldContacts.isEmpty() && oldContacts.get(ct.Id) != null
                && ct.Email != oldContacts.get(ct.Id).Email) {
                ct.Email = oldContacts.get(ct.Id).Email;
            }
        }
        return contacts;
    }

    private static List<AsynchronousProcessNotification__e> setAsynchronousProcessNotificationEvents(List<Contact> contacts, Id userId) {
        List<AsynchronousProcessNotification__e> asynchronousProcessNotification = new List<AsynchronousProcessNotification__e> ();
        for (Contact ct : contacts) {
            asynchronousProcessNotification.add(new AsynchronousProcessNotification__e(UsersToNotify__c = userId,
                                                                                       RefreshRecordsViewPage__c = true,
                                                                                       RefreshObjectsListViews__c = true,
                                                                                       DisplayNotification__c = true,
                                                                                       ToastNotificationMode__c = 'sticky',
                                                                                       ToastNotificationVariant__c = 'error',
                                                                                       ToastNotificationMessage__c = Label.EmailAddressAlreadyExists,
                                                                                       RecordName__c = ct.FirstName + ' ' + ct.LastName,
                                                                                       RecordId__c = ct.Id,
                                                                                       ObjectApiName__c = 'Contact'));
        }
        return asynchronousProcessNotification;
    }

}